version: "2"

services:
  ########################################################
  ### KAFKA CLUSTER
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.4.12
    restart: "unless-stopped"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
  kafka-0:
    # image: docker.io/bitnami/kafka:1.1.0
    build: ./kafka
    restart: "unless-stopped"
    ports:
      - "19090:9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_0_data:/bitnami/kafka
      - ./kafka/config/server-0.properties:/opt/bitnami/kafka/conf/server.properties
    depends_on:
      - zookeeper
  kafka-1:
    # image: docker.io/bitnami/kafka:1.1.0
    build: ./kafka
    restart: "unless-stopped"
    ports:
      - "19091:9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_1_data:/bitnami/kafka
      - ./kafka/config/server-1.properties:/opt/bitnami/kafka/conf/server.properties
    depends_on:
      - zookeeper
  kafka-2:
    # image: docker.io/bitnami/kafka:1.1.0
    build: ./kafka
    restart: "unless-stopped"
    ports:
      - "19092:9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_2_data:/bitnami/kafka
      - ./kafka/config/server-2.properties:/opt/bitnami/kafka/conf/server.properties
    depends_on:
      - zookeeper
  ########################################################
  ### UIs
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "unless-stopped"
    ports:
      - 8080:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-0:9092,kafka-1:9092,kafka-2:9092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: "unless-stopped"
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  kowl:
    image: quay.io/cloudhut/kowl:master
    restart: "unless-stopped"
    ports:
      - 8082:8080
    environment:
      KAFKA_BROKERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
  akh:
    image: tchiotludo/akhq
    restart: "unless-stopped"
    ports:
      - 8083:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
  ########################################################
  ### Metrics
  kafka-minion:
    image: quay.io/cloudhut/kminion:master
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
  kafka-exporter:
    image: danielqsj/kafka-exporter
    restart: unless-stopped
    command:
    - '--kafka.server=kafka-0:9092'
    - '--kafka.server=kafka-1:9092'
    - '--kafka.server=kafka-2:9092'
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    # dashboards:
    # jmx: https://grafana.com/grafana/dashboards/721
    # jmx: https://grafana.com/grafana/dashboards/762
    # kafka-minion: https://grafana.com/grafana/dashboards/14012
    # kafka-minion: https://grafana.com/grafana/dashboards/14013
    # kafka-minion: https://grafana.com/grafana/dashboards/14014
    # kafka-exporter: https://grafana.com/grafana/dashboards/7589
    image: grafana/grafana
    ports:
      - "9091:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config/provisioning:/etc/grafana/provisioning
      - ./grafana/config/dashboards:/var/lib/grafana/dashboards

volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.66.47.0/24
          gateway: 10.66.47.1
