global:
  scrape_interval: 5s
scrape_configs:
- job_name: 'kafka'
  static_configs:
  - targets: 
    - kafka-0:9095
    - kafka-1:9095
    - kafka-2:9095
- job_name: 'kafka-minion'
  static_configs:
  - targets: 
    - kafka-minion:8080
- job_name: 'kafka-exporter'
  static_configs:
  - targets: 
    - kafka-exporter:9308
