{
 "title": "KMinion Consumer Group Dashboard - Prometheus Exporter for Apache Kafka",
 "description": "Kafka Topic metrics exported by KMinion",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": "label_values(kminion_kafka_consumer_group_topic_lag, group_id)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\"}, topic_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumergroup => Topic Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "Offset Commit Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum by (kubernetes_pod_name) (rate(kminion_kafka_consumer_group_offset_commits_total{group_id=\"$consumerGroup\"}[1m])))"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic_name}}"
    },
    {
     "expr": "avg by (topic_name, group_id) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\", topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic_name}}"
    }
   ]
  }
 ]
}